### ISSUE TITLE
Which is which?

### ISSUE THREAD

**Issue by larigyn** [vitalets/x-editable#1000]
Hello,

I'm looking for editable grids and I came up with Jq Widgets, data table, and this one (x-editable). I'm reading much of the documentations and I found most documentation good in both two but in X-Editable I would rather ask. I'm using CI and I want to integrate x-editable for the editable grids. Does this one has a minimal learning curve? I also found out that there are few tutorials for the usage of this library.

thanks :)

**Comment by MarQuisKnox** [comment]
I found X-editable easy to use, but for grid editing (for example:  editing multiple fields at once) I would choose another project. Otherwise you will have to manually implement a lot of logic. I experienced this issue while building an issue tracker.
