### ISSUE TITLE
x-editable & select2 weird issue

### ISSUE THREAD

**Issue by notrosh** [vitalets/x-editable#1008]
Hi all, 

As the title states I am using x-editable with the select2 option.  I am using the multiple selection option.  Everything works great except when I click the remove button (Figure 1).

![image](https://cloud.githubusercontent.com/assets/420911/26269009/d55bc23e-3cb7-11e7-8ce8-bca2ddc27caa.png)

After clicking it the inline editor is correct

![image](https://cloud.githubusercontent.com/assets/420911/26269020/eda29b2e-3cb7-11e7-8db6-c60ca3d5ae25.png)

But I end up with the select2 drop down content at the top left of the page at absolute 0,0.

![image](https://cloud.githubusercontent.com/assets/420911/26269062/3f901f88-3cb8-11e7-825d-dd04d5b1c8fa.png)

I have a ghetto fix that utilizes the success option in x-editable that grabs <span> it's sitting in and remove it from the DOM.  However, it still flashes which looks super ghetto. 

What have I missed? 

Great tool here....

Cheeers, 

-n

**Comment by notrosh** [comment]
Does anyone have any thoughts on this?

**Comment by MarQuisKnox** [comment]
Please setup a demo on [JS Bin](https://jsbin.com) or [JS Fiddle](https://jsfiddle.net)

**Comment by notrosh** [comment]
Thanks for the reply.  I ended up scraping it and going with a different approach. 

Thanks, 

-n

**Comment by clarkeyes** [comment]
display: function (value, sourceData) {
            console.log(sourceData);
            //set new text for xeditable field from php response 
            $(this).text(sourceData);
        }

you need rewrite this function.
