### ISSUE TITLE
max length option for text input

### ISSUE THREAD

**Issue by ShahnazK** [vitalets/x-editable#1011]
I believe there is no such option to set the max length for text input. we need to validate manually. can you please add that as an option so that developer can set?

**Comment by MarQuisKnox** [comment]
It has been added:  https://github.com/vitalets/x-editable/pull/990/files

**Comment by ShahnazK** [comment]
it's not working for me, i have created [fiddle](http://jsfiddle.net/shahnaz/p7bq24xs/) to show this. can you please tell me what i am doing wrong here?

**Comment by MarQuisKnox** [comment]
The correct JS file is `dist/bootstrap-editable/js/bootstrap-editable.js`

**Comment by ShahnazK** [comment]
after adding this version i am getting `$.fn.popover.defaults is undefined`. when this update will be available for latest CDN js?
