### ISSUE TITLE
I do not want to show edit buttons，What should I do？

### ISSUE THREAD

**Issue by lizongwen** [vitalets/x-editable#1019]
I do not want to show edit buttons，What should I do？

**Comment by Estrusco** [comment]
If you intend the confirm and cancel button, you can set showbuttons to false in editable.

``'js
    $('#myID').editable(
    { 
        showButtons: false
    });
``'

**Comment by Smtgr14** [comment]
The option needs to be formatted as
```showbuttons: false```
Camel case seems to be incorrect.

**Comment by Estrusco** [comment]
Yes, without camel case :)
