### ISSUE TITLE
Select2 multiple not working

### ISSUE THREAD

**Issue by lk77** [vitalets/x-editable#1039]
Hello,

it seems that setting multiple in select2 config is not working,
because multiple parameter is ignored when select2 is used on a select element

it's a problem with my version of select2 ?
i have version 4.0.3 for select2 and 1.4.6 for X-editable

thanks

**Comment by lk77** [comment]
It is working with select2 3.4.4, 
so i will wait for a support for 4.0.3

**Comment by Bencool** [comment]
Same problem here, any help?
