### ISSUE TITLE
[Bug] When input type is 'number', elem.setSelectionRange results in error.

### ISSUE THREAD

**Issue by mdeweerd** [vitalets/x-editable#1052]
Hi
I've set the input type to 'number'  but then I got
 VM1751:1 Uncaught DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.
    at eval (eval at setCursorPosition (http://localhost/locbox/assets/344a78e8/js/jqueryui-editable.js?oosk4t:25:1222),

Basically for this piece of code:

```
setCursorPosition: function(elem, pos) {
       if (elem.setSelectionRange) {
            elem.setSelectionRange(pos, pos);
       } ,

```
The function 'setSelectionRange' exists on the element, but it is not supported by the element type.

**Comment by mdeweerd** [comment]
I tried to reproduce it in a fiddle, but I get another error:
http://jsfiddle.net/le_top/2aus4en9/

**Comment by theshadow124** [comment]
I started getting this same error last night out of seemingly nowhere. Is this something that could have been introduced in a very recent update?

**Comment by mdeweerd** [comment]
Closing request that is open since almost 1 year to relieve the Dolibarr team.  Can live with - does not happen very often.

**Comment by jcairney** [comment]
This is still an issue and should be reopened.

**Comment by theshadow124** [comment]
@jcairney I have got this error quite a few times, every single time it has actually originated from another error on the page. I was trying to reproduce the error to give an example but I was unable to. Try creating an empty HTML page with only the minimum required libraries and see if you still get the error. If you do please post it here so we can have a test case for the error.
