### ISSUE TITLE
SOLUTION X-editable for BS-4

### ISSUE THREAD

**Issue by ilramdhan** [vitalets/x-editable#1189]
**To use x-editable on BS-4**
1. You just need to download the css and js manual for BS-4 in here: [https://github.com/Talv/x-editable/tree/develop/dist/bootstrap4-editable](url). 
2. And insert the bootstrap4-editable file into your project.
3. Then after that just insert the css and js into your blade. 
![x-edit](https://github.com/user-attachments/assets/ed9af595-5505-4411-9585-a63c788612db)

4. And everything work. Like this.
![tes x-edit](https://github.com/user-attachments/assets/ec66d187-d164-46ab-b229-e61682dc96a7)

Hopefully this helps those of you who are still stuck on the issue.

**Comment by ilramdhan** [comment]
Solved for BS-4

**Comment by Iquaridys** [comment]
can you make it for BS 5 too?
