### ISSUE TITLE
Datepicker in conflict with jQueryUI

### ISSUE THREAD

**Issue by Kalzem** [vitalets/x-editable#156]
I am using the x-editable bootstrap 1.4.3 and jQueryUI 1.10.1.

I am facing a conflict with the use of the native jQueryUI Datepicker.
It seems that when I create a normal datepicker with jQuery, it gets the behaviour of x-editable bootstrap.

For example, when I select a date on the datepicker, it doesn't automatically close it, even when I force it.

Also, when I create the datepicker with options, they all get ignored.

(And I did not put anything .editable() in my code)

How can I stop this behaviour to spread to native jQuery UI ?

![Alfred-Screenshot](https://f.cloud.github.com/assets/1152371/241014/e47ff1ea-8974-11e2-8c95-407a69803804.png)

**Comment by shahidkarimi** [comment]
How to fix this issue. It is conflicting with JQuery UI
