### ISSUE TITLE
how to disable editable after enabled

### ISSUE THREAD

**Issue by troseman** [vitalets/x-editable#160]
I turn on .editable() and later want to turn this off. I tried this:
 $('#myselector').editable( { disabled: true } );
but this doesn't work, click element still allows editing.

What is the right way to turn off editable() ?
thanks

**Comment by prijuly2000** [comment]
can i not use this for my project. I want to use this editable code as template for my project. I find this reusable. Could you please walk me through it. How to use it? I dont seee an option to download this code. Thank you.

**Comment by reposman33** [comment]
I am looking for a property on a text field that when true, lets the user edit the field, if false not. Like this
<span
	editable-text="user.name"
	onbeforesave="update($data)"
	editable="column.cell_editable"
	class="form-control">{{user.name}}</span>
The property 'editable' is not doing anything so I wonder is this possible?

**Comment by cavemanbravo** [comment]
Is there an easy way to let your entire form default as uneditable?
