### ISSUE TITLE
Enable buttons to be displayed at the bottom instead of at the right

### ISSUE THREAD

**Issue by dplanella** [vitalets/x-editable#198]
Quite often horizontal space is limited (especially for mobile devices), whereas vertical space is not. Particularly, the two ok and cancel buttons steal quite a lot of the horizontal space. I'm finding this in a project where I'm adding editing features to the names of (narrow) thumbnails, and I've had to resort to `'popover'` mode instead of `'inline'`, as in inline mode there was no physical space to type.

It'd be nice if X-editable would provide an option to show the ok and cancel buttons at the bottom of the editable input instead of at the right, similarly to what [Trello](www.trello.com) does.

Here's a screenshot:
![Trello inline](https://f.cloud.github.com/assets/1689781/347242/f8ea162e-9eaf-11e2-9904-d36dadc46cdb.png)

**Comment by nillith** [comment]
So, Is it possible now?
