### ISSUE TITLE
inline form will not close

### ISSUE THREAD

**Issue by joekaiser** [vitalets/x-editable#211]
I am using the bootstrap build (latest bootstrap, x-editable 1.4.3) 

When x-editable runs in popup mode everything is awesome. Inline mode is not so awesome :( 

The inline form never closes. When i click the X it does nothing, and submit does nothing if I _don't_ change the value. If I do change the value, it does go away, but the extra DOM space isn't removed (almost like it gets set `visibility:hidden` instead of `display:none`)

I have tracked it down to the hide(reason) method. The first check it does is `if(!this.tip() || !this.tip().is(':visible') || !this.$element.hasClass('editable-open'))` and for some reason the tip is **not** visible.  It should be though because I can see it, and I click the button :)

Any ideas why tip is showing as hidden?

**Comment by ziaulrehmandevsinc** [comment]
Thank-you @jayschab, this solved the issue, seems like the readme file tells us about including css in such a way it can be easily missed. Should be more prominent like js including instructions.
