### ISSUE TITLE
Cannot disable cache for select source url

### ISSUE THREAD

**Issue by asacarter** [vitalets/x-editable#218]
Hi

I am unable to disable the cache when using a select and getting data from a source url. I have tried setting sourceCache: false but it doesn't seem to make any difference. I have also tried setting it with the data attribute and in the ajaxOptions.

I would like to get the data from the server every time the editable is shown - not just the first time.

My code is below. I don't submit anything to the server. I only update a data attribute. 

```
$('.quantity-editable').editable({
        showbuttons: false,
        type: 'select',
        sourceCache: false,
        ajaxOptions: {
            cache: false,
            type: 'POST'
        },
        display: function(value, sourceData) {
            var html = [],
            selected = $.fn.editableutils.itemsByValue(value, sourceData);
            if (selected.length) {
                $.each(selected, function(i, v) {
                    tickets = (v.value > 1) ? ' Tickets' : ' Ticket';
                    value = v.value;
                    html.push($.fn.editableutils.escape(v.text));
                 });
                $(this).html(html + tickets);
                $(this).closest('td').find('.collect-ticket').data('quantity', value);
            } else {
                $(this).empty();
            }
        }
    });
```

In the success callback of an ajax request that updates some data in the backend I have also tried this:

```
var opts = $(_this).closest('tr').find('.editable').data('editable').options;
$(document).removeData(opts.source+'-'+opts.name);
```

Nothing I have tried seems to disable the cache :(

Thanks

Asa

**Comment by mediaceh** [comment]
It don't work for me absolutely. Ver 1.5.1.
