### ISSUE TITLE
input mask not working? SOLVED

### ISSUE THREAD

**Issue by paeon** [vitalets/x-editable#221]
Hi, I need to use an input mask, have tried
with the on.shown event

$('#username').on('shown', function () {
    $(this).data('editable').input.$input.mask('999');
});

Could only get this to work with jquery-1.8.2.min

Tony

**Comment by AmaliDeveloper** [comment]
Hey you can get the solution for this problem here Good Work [Link](https://youtu.be/dV3s7s_8fnE)
