### ISSUE TITLE
multiselect is a must

### ISSUE THREAD

**Issue by bdsoha** [vitalets/x-editable#244]
hello,
your plugin is amazing and super helpful.
I think that a multiselect option is a must.
wordpress integration would also be nice.
thanks

**Comment by cpsarathe** [comment]
I have created a customized dropdown which allows to select multivalues , allow to submit multivalues and display multivalues.

https://github.com/cpsarathe/CXEditable/blob/master/WebContent/resources/js/editable-multi-select.js
![multiselect](https://cloud.githubusercontent.com/assets/13636425/11264824/05c16cb2-8ebd-11e5-8178-c93c665cb956.png)

**Comment by ambitdev1** [comment]
@cpsarathe ... thanks you made my day... i had done lot of rnd on select2 with xeditable... but its not working ... your code is awesome.

**Comment by unnayan-acharekar** [comment]
Thanks @cpsarathe
