### ISSUE TITLE
getValue for single element

### ISSUE THREAD

**Issue by AaronLS** [vitalets/x-editable#259]
Feature request: Using getValue can be pretty complicated when dealing with a single editable, given that after the call to getValue, you still need to do .whateverElementNameIs to access the value.  I have encountered several use cases that this makes things complicated.  It would be nice if there were a getValue that retrieved the value directly:

http://jsfiddle.net/xBB5x/1306/

**Comment by abelvf30** [comment]
Please anybody can help me with this?

http://stackoverflow.com/questions/29473716/x-editable-post-method
