### ISSUE TITLE
Disabling click out

### ISSUE THREAD

**Issue by doomed51** [vitalets/x-editable#293]
Is there a way to disable being able to click out of the editing state. Basically what I'm trying to do is to get the user to only use the confirm or cancel buttons when an item is opened for editing. This way when the user clicks anywhere else on the screen the field that is being edited remains in its editable form. 

haven't been able to figure out how to do this or maybe I missed a setting somewhere.

**Comment by spidergears** [comment]
@vitalets I have run into a similar issue. The fields do not remain open for editing when click outside of form. Here is my config

```
$('#ots-seller tbody tr .price')
  .editable({
    onblur: 'ignore',
    mode: 'inline'
})
```
