### ISSUE TITLE
TypeError: this.container(...)._off is not a function

### ISSUE THREAD

**Issue by campa** [vitalets/x-editable#32]
Can anyone suggest me to solve this error:

TypeError: this.container(...)._off is not a function
..... /js/jquery/jqueryui-editable/js/jqueryui-editable.js
Line 2438

Using inline way it works fine.

Any ideas ?

I'm using:
- X-editable - v1.1.1 
- jQuery JavaScript Library v1.8.2
- jQuery UI - v1.9.1 - 2012-10-25

**Comment by faravaghi** [comment]
ca you change and fix on x-editable-yii?
