### ISSUE TITLE
Programmatically open select2

### ISSUE THREAD

**Issue by Zolrag** [vitalets/x-editable#322]
Hi,

I am trying to open the select2 on 'shown'.

Here is the code:
$(".edit_in_place").on('shown', function(e, editable) {
     $(".input-medium").select2("open");
 });

The shown and open events are correctly triggered but the dropdown menu doesn't display properly. The search bar appears in the top left corner of the window as you can see on the screenshot. After scrolling a bit, the dropdown puts itself together but if I click on another editable element things start to get wild (a video would be required to show the crazy behavior). Everything works fine if I open the dropdown manually though. I am not sure what I am doing wrong.
Help would be greatly appreciated :).

![screen shot 2013-07-30 at 3 57 32 pm](https://f.cloud.github.com/assets/1544148/879027/32134270-f920-11e2-8700-60b02f1c255d.png)

**Comment by tlg25** [comment]
Thank a lot for Vitalets! I have the same problem today (About top left corner). I am only beginner in the web-programming and can't solve this problem during whole day.  And only in this topic I found decision of the problem. It is work!

**Comment by exodus4d** [comment]
If you don´t like the `timeout()` this works as well:

``` JS
$.when(
    selectElement.select2();
).done(function(){
     selectElement.select2('open');
});
```
