### ISSUE TITLE
x-editable not working on pagination

### ISSUE THREAD

**Issue by syphon1c** [vitalets/x-editable#326]
I didnt see a previous posting or perhaps I am doing something wrong. However I have x-editable working just fine using bootstrap datatables, however I noticed that the x-editable items in the table not on the first page...from page 2,3,4...are not working, they're highlighted but I cant edit them inline.

I have uploaded two screenshots below, you can see the difference from page 1 to the next...

Any help would be much appreciated

Anyone see this before?
![screen shot 2013-08-01 at 1 24 49 pm](https://f.cloud.github.com/assets/1331997/893281/f47fff10-fa9c-11e2-86a6-27b5682ac842.png)
![screen shot 2013-08-01 at 1 24 38 pm](https://f.cloud.github.com/assets/1331997/893282/f6c209c6-fa9c-11e2-8e78-7a55572e89af.png)

**Comment by husnixs** [comment]
I've try the code above and work perfectly.
now I have new problem, how about if using datatable serverside.
anyone ever try it..??

**Comment by ajaygangarde** [comment]
Heyy Man sraza123 
Thanks.. u saved my Day..

**Comment by monday41** [comment]
I use like this:
```javascript
                "fnDrawCallback": function() {
                    $('.stock').editable();
                }
```

**Comment by kalu8** [comment]
Hi, I´m having issues too with pagination, I tried all the solution posted here, but nothing works for me :(

I have this:


		 "fnDrawCallback": function(){
						var contador = '<?php echo $contador?>';
					   $('#codigo_pep_'+contador).editable({ //called by id
				    	 Emptytext: 'Codigo PEP',
				    	 url: 'actualiza_codigo_pep.php', 
				         title: 'Codigo PEP nuevo',
				         rows: 10				        
				      });
				};		

But still have the issues mentioned above, any ideas...???

**Comment by enboig** [comment]
Same issue as @kalu8; I just want one cell editable, and set a diferent title to ensure user is editing intended cell:

>
>"fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
>      var thiscell = '#' + aData['DT_RowId'] + " .agrupament-estat";
>      console.log(thiscell);
>      $(thiscell).editable({
>        mode: "popup",
>        title: 'Edit ' + aData[2],
>        source: [
>          {value: 2, text: "two"},
>          {value: 3, text: "three"}
>        ]
>      });
>    }

Any hint?

**Comment by husnixs** [comment]
I use this, and work perfectly
"fnDrawCallback": function ( oSettings ) {

            $(".edit").editable({
                mode : 'popup',
                container: 'body',
                emptytext : '-',
                ajaxOptions : {
                    type : 'post'
                },
                success: function(data) {
                    $("#success").show();
                },
                error: function(response, newValue) {
                    if(response.status === 500) {
                        return 'Service unavailable. Please try later.';
                    } else {
                        return response.responseText;
                    }
                }
            });
}

**Comment by enboig** [comment]
Strange, it is working in "fnDrawCallback" but wasn't in "fnRowCallback".

fnRowCallback was running (I could see it in console log), now it is a little of overkill, the function is called for every row (~200) everytime I change page (pagination set at 10)

**Comment by jp-mohapatra** [comment]
use it in" createdRow", It worked for me. :)

**Comment by robertnicjoo** [comment]
If you have `multiple editable parts` in your page and using `datatable.js` this is how it works.

```javascript
<script>
    $(document).ready(function() {
        var table = $('#mydata').DataTable({
            "fnRowCallback": function( nRow, mData, iDisplayIndex, iDisplayIndexFull) {
                // add x-editable
                $.fn.editable.defaults.mode = 'inline';
                $.ajaxSetup({
                     headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
    
                product_id = $(this).data('pk');
                url = $(this).data('url');
                
                //make stock editable
                $('.stock').editable({
                    url: url,
                    pk: product_id,
                    type:"text",
                    validate:function(value){
                      if($.trim(value) === '')
                      {
                        return 'This field is required';
                      }
                    }
                });
                
                //make weight editable
                $('.weight').editable({
                    url: url,
                    pk: product_id,
                    type:"text",
                    validate:function(value){
                      if($.trim(value) === '')
                      {
                        return 'This field is required';
                      }
                    }
                });
                //make price editable
                $('.price').editable({
                    url: url,
                    pk: product_id,
                    type:"text",
                    validate:function(value){
                      if($.trim(value) === '')
                      {
                        return 'This field is required';
                      }
                    }
                });
                //make discount price editable
                    $('.newprice').editable({
                    url: url,
                    pk: product_id,
                    type:"text"
                });
                // using class not id, since likely used with multiple records
                $('.status').editable({
                  // Note: cleaner to format in the controller and render using the json directive
                  source: [
                      @foreach($statuses as $status)
                          { value: '{{ $status->id }}', text: '{{ $status->title }}' }
                          @unless ($loop->last)
                              ,
                          @endunless
                      @endforeach
                  ]
                });
            },
            //
        });
    });
</script>
```

**PS** If you have only one part you can use this code (it's same as code above just shorter)

```javascript
<script>
    $(document).ready(function() {
        var table = $('#mydata').DataTable({
            "fnRowCallback": function( nRow, mData, iDisplayIndex, iDisplayIndexFull) {
                // add x-editable
                $.fn.editable.defaults.mode = 'inline';
                $.ajaxSetup({
                     headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                product_id = $(this).data('pk');
                url = $(this).data('url');
                
                //make stock editable
                $('.stock').editable({
                    url: url,
                    pk: product_id,
                    type:"text",
                    validate:function(value){
                      if($.trim(value) === '')
                      {
                        return 'This field is required';
                      }
                    }
                });
            },
            //
        });
    });
</script>
```

**Note**

Don't worry about my code that includes `ajaxheader` or `dataPK` etc. you can just remove those parts based on your app environment.

Hope it helps

**Comment by mitramitro** [comment]
Just Change Position javascript like this: (I'm run with this)
before:
<script>
    $(document).ready(function(){
        $('#datatable').dataTable( {
bla...bla......
</script> 

<script>
  $(document).ready(function() {
    $('.statusrebel').editable({
      
        value: 1,    
        source: [
              // {value: "nostatus", text: 'No Status'},
              {value: "done", text: 'Done'},
              {value: "rebilling", text: 'Rebilling'}
           ]
    });
});
</script>

Become:
<script>
  $(document).ready(function() {
    $('.statusrebel').editable({
      
        value: 1,    
        source: [
              // {value: "nostatus", text: 'No Status'},
              {value: "done", text: 'Done'},
              {value: "rebilling", text: 'Rebilling'}
           ]
    });
});
</script>

<script>
    $(document).ready(function(){
        $('#datatable').dataTable( {
bla...bla......
</script>

**Comment by mitramitro** [comment]
script editable
then
script datatable

**Comment by ahugo91z** [comment]
> I use x-editable along with datatables.
> Think [fnRowCallback](http://datatables.net/ref#fnRowCallback) is what you need.
> 
> I use like this;
> 
> ```js
> var oTable = $('#myDataTable').dataTable( {
>   // .... some datatables init option
>   // ..
>   // add x-editable to my fields with fnRowCallback
>   "fnRowCallback": function( nRow, mData, iDisplayIndex ) {
>     // create link
>     $('td:eq(2)', nRow).html('<a class="myeditables-class" href="#">' + RoWContent + '</a>');
>     // add x-editable
>     $('td:eq(2) a', nRow).editable({
>       //..
>       //.. x-ediable options here 
>       //..          
>       });
>     return nRow;
>     },
> } );
> ```
> 
> Or my quick hack example on [jsfiddle](http://jsfiddle.net/nASTU/4/)

Thanks for the code, works for me!!! I'm from Guatemala!!!
