### ISSUE TITLE
[Select] set currently selected as default value

### ISSUE THREAD

**Issue by boldtrn** [vitalets/x-editable#332]
Hi,

I know about the `value` tag in js. So I could allways pass `value: 1` or something to every element. But is it also possible to have the currently selected value as the default value?

**Comment by AngelVenchev** [comment]
Hi, I have the same issue as the original poster, however the last jsfiddle provided by @vitalets does not work anymore and that is what I need. Do you think it's possible to fix it.

**Comment by bhoriuchi** [comment]
this is what I do and it seems to work fine

html
<pre>
&lt;span 
data-xeditable="true" 
data-type="select" 
data-sourceCache="true" 
data-source="/path/to/source"&gt;<i><b>value of selection<b></i>&lt;/span&gt;
</pre>

javascript
```js
$('[data-xeditable="true"]').editable({
    autotext: 'always'
});
```

**Comment by jcsto** [comment]
if you use the remote json array, when you specify de attribute in the HTML: data-value="1", it's going to load the selected value.
E.g. 
remoteFile.php
`$a = [
    ['value'=>"1", 'text' => 'yes'],
    ['value'=>"0", 'text' => 'no'],
];
header('Content-type: text/json');
echo json_encode($a);`

HTML file:
`<a href="javascript:;" id="options" data-type="select" class="editable-field" data-source="includes/remoteFile.php" data-original-title="Select option" data-value="0">no</a>`

When the plugin is called, it's going to show the "no" option by default at first.

**Comment by lazybotter** [comment]
Hi, can anyone help me with this one? 

When using the "select" type why is the "text" passed to the success(response,newVALUE) callback? And not the value? Is there an option I can set to enable this?

**Comment by oawebdev** [comment]
Dosn't work with select2 ajax source.
