### ISSUE TITLE
Not all items editable when using a PHP foreach loop to generate a table

### ISSUE THREAD

**Issue by dyelton** [vitalets/x-editable#342]
I would love to give you a jsfiddle for this but I can't since it will only allow me to give HTML which doesn't seem to have the issue.

If I make a table in a PHP foreach loop like so:

``` php
foreach($results as $row) {
            echo '<tr>';
            echo '<td>' . $row['DATE_YYYYMMDD'] . '</td>';
            echo '<td><span class="time" data-type="text" data-pk="'.$row['ID'].'">'.$row['CLOCK_IN'].'</span></td>';
            echo '<td><span class="time" data-type="text" data-pk="'.$row['ID'].'">'.$row['CLOCK_LUNCH_OUT'].'</span></td>';
            echo '<td><span class="time" data-type="text" data-pk="'.$row['ID'].'">'.$row['CLOCK_LUNCH_IN'].'</span></td>';
            echo '<td><span class="time" data-type="text" data-pk="'.$row['ID'].'">'.$row['CLOCK_OUT'].'</span></td>';
            echo '<td>' . 'TOTAL' . '</td>';
            echo '</tr>'; }
```

...the results on screen are what I expect and all 'x-editable' links appear correctly, but something strange happens. All of the first column's items are editable, but for all other columns, it seems to be completely random which ones are editable. Clicking on some items will give me the popup to edit where others will not. I'm about to pull my hair out on this one!

**Comment by phpusrpro** [comment]
Same issues https://preprocessor.space/questions/incorporating-a-modification-option-within-a-php-foreach-loop-for-tables
