### ISSUE TITLE
Issues with Jquery unobtrusive 

### ISSUE THREAD

**Issue by OldSchoolDev-zz** [vitalets/x-editable#384]
Hey guys,

I am facing some issues with x-editable and unobtrusive validation.

I have jquery validate and jquery validate unobtrusive libraries in my project.

The issue is when I have the trigger inside a form. As x-editable renders another form, it will have a form inside another form and it is causing the problem with the validation libraries. Unfortunately, I need to keep the validation libraries and I can't remove either the form (because it is a asp.net webforms) or the validation.

The message displayed after clicking on the anchor is: Uncaught TypeError: Cannot read property 'settings' of undefined

This happens in inline mode....

Sorry, but I don't know if it is something related with jquery validation or x-editable.

Please, check this fiddle. It will show my problem.

http://jsfiddle.net/xBB5x/2159/

Thanks

**Comment by thorne51** [comment]
> yes, it's one of pitfails of current x-editable - it always renders form tag that can lead to nested forms..
The workaround for your case can be to copy validator property from outer form to inner. 
Please try it, but re-check that everything works 
http://jsfiddle.net/xBB5x/2262/

>`$('#username').on('shown', function() {
    var $innerForm = $(this).data('editable').input.$input.closest('form');
    var $outerForm = $innerForm.parents('form').eq(0);
    $innerForm.data('validator', $outerForm.data('validator'));
});`

This workaround seems to work so far, except when I use the Enter key to close/submit the x-editable inline field. Then the exception is thrown again

**Comment by fernandofagundes** [comment]
thanks Vilalets, it's work;

$('#username').on('shown', function() {
    var $innerForm = $(this).data('editable').input.$input.closest('form');
    var $outerForm = $innerForm.parents('form').eq(0);
    $innerForm.data('validator', $outerForm.data('validator'));
});
