### ISSUE TITLE
Modify some defaults options for all editable-elements

### ISSUE THREAD

**Issue by Alex-Sokolov** [vitalets/x-editable#418]
I have initializations for many types of field, but all have common options.
Starting trying to set needed common options through defaults:

``` js
// Look before
console.log($.fn.editable.defaults);

$.fn.editable.defaults = $.extend({
    inputclass: 'input-xxlarge',
    mode: 'inline',
    emptytext: 'Пусто',
    onblur: 'submit'
}, $.fn.editable.defaults);

// Look after
console.log($.fn.editable.defaults);
```

Options for `inputclass`, `mode`, `onblur` added ok, but `emptytext` anyway with default value `Empty`.

What I'm doing wrong?

P.S.:
X-editable 1.5.0
jQuery 1.10.2

**Comment by Vicente167** [comment]
it works!!!. thanks
