### ISSUE TITLE
Do not allow null or empty input val

### ISSUE THREAD

**Issue by arturoromero-4th** [vitalets/x-editable#424]
Hello guys i have a problem , I´m trying to use .editable like this:
When a user clicks on a button the edit appears and when it clicks on save the record is stored on the database and then on successful an append is made on the html to make it look like the record is been refreshed from the DB, but when i click again to add another record the input text is the last one i put on the saved field, and if i try to editable('setValue', null) the input gets cleared but the user is able to submit null values, so what i want to know is how can i deny null or empty input values on submit. Thank you so much , here is a part of the code that does this:

jQuery("#tableMDT").on("click",".add_comment", function (e){
    e.stopPropagation();
    jQuery("input[name=cr_comments]").val('');
    request_id = jQuery(this).attr('data');
    var comment_area = jQuery(this).attr("id"); 
    jQuery(".add_panel").css('display','none');
    jQuery("#comment_id_"+comment_area).css('display','block');
    jQuery(".add_comment").show();
     jQuery('#'+request_id).editable({
      type: 'text',
      url: '/submit_comments',  
      pk: request_id,
      success: function(value){

```
    jQuery('#table_'+request_id).append("<tr><td style='border:0; line-height: 12px; font-size:10px; width:270px'><strong>"+username_c+"</strong>- "+date_now+":<p style='font-style: italic; color: gray;'>"+value+"</p><hr style='margin:0; width:270px' ></td></tr> ");
    jQuery(".editableform-loading").hide();     
  },

  });
  jQuery('#'+request_id).editable("toggle");
```

  });
}

**Comment by kamarshad** [comment]
hi @vitalets i want to validate some input but dont want to return string, how i can do
validate: function(value) {
  if (value === null || value === '') {
here i want to create new css
    return '';
  }
}
