### ISSUE TITLE
setValue error in combodate

### ISSUE THREAD

**Issue by rogergithubbing** [vitalets/x-editable#429]
Hello,

I'm using the Combodate plugin included in X-EDITABLE bootstrap-editable-1.4.6, and I'm getting this error using setValue (to set the initial value for the control) AFTER initializing the control with the first $('#myDate').editable(..) call.

Then, the second time I use .editable:

```
$('#myDate').editable('setValue', '03-04-2016'); // This is my date format, it's ok...
```

... I'm getting this error:

_0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'format'_

So, I've ended up using this horrible document.write piece of 'code', where myDateValue is a Javascript var assigned before:

```
<div class="row" id="row1">
  <div id="r1c1" class="span5">
    <div class="control-group">
      <label class="control-label">Here goes my date</label>
      <div class="controls">
        <script>
          document.write('<a href="#" id="myDate" data-type="combodate" data-pk="1" data-placement="bottom" data-value="' + varMyDateValue + '" ></a>');
        </script>
      </div>
    </div>
  </div>
```

Why I'm getting that error ?

Thanks in advance,

Roger

**Comment by aadilttec** [comment]
@vitalets could you please help me with this issue?

Error message when I ran the script in IE11, **"Object doesn't support property or method 'combodate'"** and it does not load drop down of date and time in a html form, it just show input text
