### ISSUE TITLE
how to send header?

### ISSUE THREAD

**Issue by phorisc** [vitalets/x-editable#441]
Hey @vitalets how do i send a header with apikey and apiuser with editables? (i am using tastypie and it requires the user and key) I tried doing the beforesend field xhr.setRequestHeader but it continues to ask me to enter in the user and pass manually.

**Comment by nadysaptra** [comment]
@aop 
i think you can do this by setup the headers in $.ajaxSetup before $(...).editable():


`$.ajaxSetup({
            headers: {
                'Authorization': Token,
                'Content-Type': 'application/json'
            },
        });
        $('#fullname').editable({
url: ..., params: function(params){ var data = [];  data['id'] = params.pk; return data; }})
`
