### ISSUE TITLE
icon instead of text

### ISSUE THREAD

**Issue by qcol** [vitalets/x-editable#450]
I tried to put icon instead of default empty value text:

http://fortawesome.github.io/Font-Awesome/icon/pencil/

``` HTML
<i class="fa fa-pencil"></i> fa-pencil
```

but after icon click, x-editable displays the text instead of textarea. After click, Icon is doubled. How to replace default text by Icon? If text is very long, I want to show only icon, text preview when icon clicked. Is it possible?

**Comment by pradippatel1411** [comment]
HTML
`<i id="VStatus_" data-value="1" data-pk="5" class="pointerTag fa fa-check-circle text-success VdStatus" title="Active"></i>`

JS code
//js code start
$('.VdStatus').editable({
                        type:"select",
                        url: "/Vendor/ToggleVendorStatus",                     
                        title: 'Change Vendor Status',
                        emptytext: ' ',
                        params: function(params) {  
                            var data = {};
                            data['id'] = params.pk;
                            return data;
                        },
                        source: [
                          {value: 1, text: 'Active'},
                          {value: 0, text: 'Inactive'},             
                        ],
                        success: function (data) {
                            if (data.Result == "OK") {
                                var vendorid = parseInt($(this).attr("data-pk"));
                                setTimeout(function () {
                                    $("#VStatus_" + vendorid).text('');
                                }, 500);

                               //your logic after success ajax.
                            } else {
                                alert(data.Message);
                            }
                            
                        }
                    });
