### ISSUE TITLE
X-Editable & PHP & MySql

### ISSUE THREAD

**Issue by PecadoX** [vitalets/x-editable#507]
Hello,

I used X-Editable plug-in and couldn't connect to database to update it. I think I must pust some code into javascript code.

Any one help me?

Thanks in advance.

Database info;

Table name is customer
column name that I wanna update is customer_name

HTML code is;

a href="#" id="customer_name" name="customer_name" data-type="text" data-placement="top" data-title="Enter New Customer Name" class="editable editable-click" data-pk="<?php echo $rowID; ?>" data-url="../includes/php/update.php"><?php echo $customer_name; ?></a

Javascript code is;

$(document).ready(function() {
    $.fn.editable.defaults.mode = 'popup';  
    $('#customer_name').editable();

And update.php code is;

$customer_name = $_POST['name'];
$ID = $_POST['pk'];
$value = $_POST['value'];

mysql_query('UPDATE customer SET ' . $customer_name . '=' . $value . ' WHERE ID = ' . $ID);

**Comment by Narender-Sharma** [comment]
i have some problam with x-editable, i get the value from sql but how to update the in sql 

html code
<a href="javascript:;" id="username" data-type="text" data-pk="1" data-original-title="Enter First Name">
<?php echo $data['first_name']; ?></a>



JavaScript code

 $('#username').editable({
            url: '/post',
            type: 'text',
            pk: 1,
            name: 'username',
            title: 'First Name',
			 validate: function (value) {
                if ($.trim(value) == '') return 'This field is required';
            }

        });
