### ISSUE TITLE
Get data-pk / id of the editable field

### ISSUE THREAD

**Issue by sveeen** [vitalets/x-editable#514]
Hey,

I develope an offline web-app (work locally) and I want to get the data-pk or id of the edited field in the success function so I can call another function with the newValue and the data-pk to reference to my internal array.

How can I get the data-pk or id?

<pre>
<b>Example from the documentation:</b>

$('#calctable a').editable({
    type: 'text',
    title: 'Enter username',
    success: function(response, newValue) {
        //call my function
        <i>thisIsMyFunc(data-pk,newValue);</i>
    }
});
</pre>

thanks for your help
Sven

**Comment by abelvf30** [comment]
Please anybody can help me with this?

http://stackoverflow.com/questions/29473716/x-editable-post-method

**Comment by pabloacevedo** [comment]
Debes agregar la opción ajaxOptions

$('#first_name')..editable({ajaxOptions: {
					type: 'POST',
					dataType: 'json' //assuming json response
				}});

**Comment by abelvf30** [comment]
This is my final code:

$('#first_name').editable({
		
		ajaxOptions: {
			type: 'POST',
			dataType: 'json'},	
	
        validate: function(value) {
		   //Not Empty	
           if($.trim(value) == '') return 'The First Name is required';
		   
		   //More than 3 and less than 20
		   if($.trim(value.length) <4) return 'The First Name must be more than 3 and less than 20 characters';
		   //Less than 20
		   if($.trim(value.length) >20) return 'The First Name must be more than 3 and less than 20 characters';	   	   
		}	
	});

AND I CONTINUE RECEIVING THE SAME ERROR when I try to capture the value with:

$first_name = $_POST['first_name'];
echo $first_name;

Result: Notice: Undefined index: first_name in.......

Please any idea?

**Comment by Tareq40** [comment]
I have problem to show image from sql to json bootstrap live edit table. please help me.
here is my code 
<body>
  <div class="container-fluid"  style="overflow-x:auto;">
   <table id="mytable" class="table table-bordered table-striped">
    <thead style="background-color: #376588; color: white; font-size: 13px;">
     <tr>
      <th>Photo</th>
      <th>Teacher Name</th>
      <th>MPO Code</th>
      <th>Gender</th>
      <th>Designation</th>
      <th>First Date of Joining</th>
      <th>Date of Joining</th>
      <th>Date of MPO</th>
      <th>Date of Birth</th>
     </tr>
    </thead>
    <tbody id="employee_data" style="font-size: 13px; color: #000000; font-weight: bolder;">

    </tbody>
   </table>
 </body>
</html>



<script type="text/javascript" language="javascript" >
$(document).ready(function(){
 
 function fetch_employee_data()
 {
  $.ajax({
   url:"fetch.php",
   method:"POST",
   dataType:"json",
   success:function(data)
   {
    for(var count=0; count<data.length; count++)
    {
     var html_data = '<tr><td>'+data[count].id+'</td>';
     html_data += '<td data-name="name" class="name" data-type="text" data-pk="'+data[count].id+'">'+data[count].name+'</td>';
     html_data += '<td data-name="gender" class="gender" data-type="select" data-pk="'+data[count].id+'">'+data[count].gender+'</td>';
     html_data += '<td data-name="designation" class="designation" data-type="text" data-pk="'+data[count].id+'">'+data[count].designation+'</td>';
     html_data += '<td data-name="age" class="age" data-type="text" data-pk="'+data[count].id+'">'+data[count].age+'</td>';
     html_data += '<?php  
 $connect = mysqli_connect("localhost", "root", "", "testing");  
 $output = '';  
 $sql = "SELECT * FROM employee ORDER BY id";  
 $result = mysqli_query($connect, $sql);  
 $output .= '<td>';  
 $rows = mysqli_num_rows($result);
 if($rows > 0)  
 {  
    if($rows > 10)
    {
      $delete_records = $rows - 10;
      $delete_sql = "DELETE FROM employee LIMIT $delete_records";
      mysqli_query($connect, $delete_sql);
    }
      while($row = mysqli_fetch_array($result))  
      {  
           $output .= '<img src="upload/'.$row["sliderPic"].'" width="70" height="80" />';  
      }  
  
 }  

 $output .= '</td> ';  
 echo $output;  
 ?></tr>';
     $('#employee_data').append(html_data);
    }
   }
  })
 }

 fetch_employee_data();
 
 $('#employee_data').editable({
  container: 'body',
  selector: 'td.name',
  url: "update.php",
  title: 'Employee Name',
  type: "POST",
  //dataType: 'json',
  validate: function(value){
   if($.trim(value) == '')
   {
    return 'This field is required';
   }
  }
 });
 
 $('#employee_data').editable({
  container: 'body',
  selector: 'td.gender',
  url: "update.php",
  title: 'Gender',
  type: "POST",
  dataType: 'json',
  source: [{value: "Male", text: "Male"}, {value: "Female", text: "Female"}],
  validate: function(value){
   if($.trim(value) == '')
   {
    return 'This field is required';
   }
  }
 });
 
 $('#employee_data').editable({
  container: 'body',
  selector: 'td.designation',
  url: "update.php",
  title: 'Designation',
  type: "POST",
  dataType: 'json',
  validate: function(value){
   if($.trim(value) == '')
   {
    return 'This field is required';
   }
  }
 });
 
 $('#employee_data').editable({
  container: 'body',
  selector: 'td.age',
  url: "update.php",
  title: 'Age',
  type: "POST",
  dataType: 'json',
  validate: function(value){
   if($.trim(value) == '')
  {
    return 'This field is required';
   }
  }
 });
 
 
 
});
</script>

**Comment by Tareq40** [comment]
html_data = '<tr><td>'+data[count].id+'</td>';
     html_data += '<td data-name="name" class="name" data-type="text" data-pk="'+data[count].id+'">'+data[count].name+'</td>';
     html_data += '<td data-name="gender" class="gender" data-type="select" data-pk="'+data[count].id+'">'+data[count].gender+'</td>';
     html_data += '<td data-name="designation" class="designation" data-type="text" data-pk="'+data[count].id+'">'+data[count].designation+'</td>';
     html_data += '<td data-name="age" class="age" data-type="text" data-pk="'+data[count].id+'">'+data[count].age+'</td></tr>';

**Comment by Tareq40** [comment]
`html_data = '<tr><td>'+data[count].id+'</td>';
     html_data += '<td data-name="name" class="name" data-type="text" data-pk="'+data[count].id+'">'+data[count].name+'</td>';
     html_data += '<td data-name="gender" class="gender" data-type="select" data-pk="'+data[count].id+'">'+data[count].gender+'</td>';
     html_data += '<td data-name="designation" class="designation" data-type="text" data-pk="'+data[count].id+'">'+data[count].designation+'</td>';
     html_data += '<td data-name="age" class="age" data-type="text" data-pk="'+data[count].id+'">'+data[count].age+'</td></tr>';`

**Comment by Tareq40** [comment]
`<body>
  <div class="container-fluid"  style="overflow-x:auto;">
   <table style="margin-top: 50px;" id="mytable" class="table table-bordered table-striped">
    <thead style="background-color: #376588; color: white; font-size: 13px;">
     <tr>
      <th>Photo</th>
      <th>Teacher Name</th>
      <th>MPO Code</th>
      <th>Gender</th>
      <th>Designation</th>
      <th>First Date of Joining</th>
      <th>Date of Joining</th>
      <th>Date of MPO</th>
      <th>Date of Birth</th>
     </tr>
    </thead>
    <tbody id="employee_data" style="font-size: 13px; color: #000000; font-weight: bolder;">

    </tbody>
   </table>
 </body>
</html>


<script type="text/javascript" language="javascript" >
$(document).ready(function(){
 
 function fetch_employee_data()
 {
  $.ajax({
   url:"fetch.php",
   method:"POST",
   dataType:"json",
   success:function(data)
   {
    for(var count=0; count<data.length; count++)
    {
     var html_data = '<tr><?php  
 $connect = mysqli_connect("localhost", "root", "", "uwkdm_database");  
 $output = '';  
 $sql = "SELECT * FROM teachers_list";  
 $result = mysqli_query($connect, $sql);  
 $output .= '<td>';  
 $rows = mysqli_num_rows($result);
 if($rows > 0)  
 {  

      while($row = mysqli_fetch_array($result))  
      {  
           $output .= '<img src="upload/'.$row["teacherPic"].'" width="70" height="80" />';  
      }  
  
 }  

 $output .= '<td>';  
 echo $output;  
 ?>'
     html_data += '<td data-name="name" class="name" data-type="text" data-pk="'+data[count].id+'">'+data[count].name+'</td>';
     html_data += '<td data-name="mpo" class="mpo" data-type="text" data-pk="'+data[count].id+'">'+data[count].mpo+'</td>';
     html_data += '<td data-name="gender" class="gender" data-type="select" data-pk="'+data[count].id+'">'+data[count].gender+'</td>';
     html_data += '<td data-name="designation" class="designation" data-type="select" data-pk="'+data[count].id+'">'+data[count].designation+'</td>';
     html_data += '<td data-name="fdoj" class="fdoj" data-type="date" data-placement="bottom" data-viewformat="dd-mm-yyyy" data-pk="'+data[count].id+'">'+data[count].fdoj+'</td>';
     html_data += '<td data-name="doj" class="doj" data-type="date" data-placement="bottom" data-viewformat="dd-mm-yyyy" data-pk="'+data[count].id+'">'+data[count].doj+'</td>';
     html_data += '<td data-name="dompo" class="dompo" data-type="date" data-placement="bottom" data-viewformat="dd-mm-yyyy" data-pk="'+data[count].id+'">'+data[count].dompo+'</td>';
     html_data += '<td data-name="dob" class="dob" data-type="date" data-placement="left" data-viewformat="dd-mm-yyyy" data-pk="'+data[count].id+'">'+data[count].dob+'</td></tr>';
     $('#employee_data').append(html_data);
    }
   }
  })
 }

 fetch_employee_data();
 
 $('#employee_data').editable({
  container: 'body',
  selector: 'td.name',
  url: "update.php",
  title: 'Employee Name',
  type: "POST",
  //dataType: 'json',
  validate: function(value){
   if($.trim(value) == '')
   {
    return 'This field is required';
   }
  }
 });

  $('#employee_data').editable({
  container: 'body',
  selector: 'td.mpo',
  url: "update.php",
  title: 'MPO',
  type: "POST",
  //dataType: 'json',
  validate: function(value){
   if($.trim(value) == '')
   {
    return 'This field is required';
   }
  }
 });
 
 $('#employee_data').editable({
  container: 'body',
  selector: 'td.gender',
  url: "update.php",
  title: 'Gender',
  type: "POST",
  dataType: 'json',
  source: [{value: "Male", text: "Male"}, {value: "Female", text: "Female"}],
  validate: function(value){
   if($.trim(value) == '')
   {
    return 'This field is required';
   }
  }
 });

 $('#employee_data').editable({
  container: 'body',
  selector: 'td.designation',
  url: "update.php",
  title: 'Gender',
  type: "POST",
  dataType: 'json',
  source: [{value: "PRINCIPAL", text: "PRINCIPAL"},{value: "1ST OFFICER", text: "1ST OFFICER"},{value: "2ND CLASS OFFICER", text: "2ND CLASS OFFICER"},{value: "3RD CLASS EMPLOYEE", text: "3RD CLASS EMPLOYEE"},{value: "4TH CLASS EMPLOYEE", text: "4TH CLASS EMPLOYEE"},{value: "ACCOUNTANT", text: "ACCOUNTANT"}, {value: "ACCOUNTS OFFICER", text: "ACCOUNTS OFFICER"},{value: "ADMINISTRATIVE OFFICER", text: "ADMINISTRATIVE OFFICER"},{value: "ASSISTANT CO-ORDINATOR", text: "ASSISTANT CO-ORDINATOR"},{value: "ASSISTANT CONTROLER", text: "ASSISTANT CONTROLER"},{value: "ASSISTANT DIRECTOR", text: "ASSISTANT DIRECTOR"},{value: "ASSISTANT HEAD MASTER", text: "ASSISTANT HEAD MASTER"},{value: "ASSISTANT INSPECTOR", text: "ASSISTANT INSPECTOR"},{value: "ASSISTANT LIBRARIAN", text: "ASSISTANT LIBRARIAN"},{value: "ASSISTANT PROFESSOR", text: "ASSISTANT PROFESSOR"},{value: "ASSISTANT PROJECT DIRECTOR", text: "ASSISTANT PROJECT DIRECTOR"},{value: "ASSISTANT PROJECT OFFICER", text: "ASSISTANT PROJECT OFFICER"},{value: "ASSISTANT REGISTRER", text: "ASSISTANT REGISTRER"},{value: "ASSISTANT SECRETARY", text: "ASSISTANT SECRETARY"},{value: "ASSISTANT SECTION TEACHER-10", text: "ASSISTANT SECTION TEACHER-10"},{value: "ASSISTANT SECTION TEACHER-6", text: "ASSISTANT SECTION TEACHER-6"},{value: "ASSISTANT SECTION TEACHER-7", text: "ASSISTANT SECTION TEACHER-7"},{value: "ASSISTANT SECTION TEACHER-8", text: "ASSISTANT SECTION TEACHER-8"},{value: "ASSISTANT SECTION TEACHER-9", text: "ASSISTANT SECTION TEACHER-9"}, {value: "ASSISTANT SUPERINTENDANT", text: "ASSISTANT SUPERINTENDANT"},{value: "ASSISTANT SUPERVISOR", text: "ASSISTANT SUPERVISOR"},{value: "ASSISTANT SUPPER", text: "ASSISTANT SUPPER"},{value: "ASSISTANT TEACHER (AGRICULTURE)", text: "ASSISTANT TEACHER (AGRICULTURE)"},{value: "ASSISTANT TEACHER (COMPUTER)", text: "ASSISTANT TEACHER (COMPUTER)"},{value: "ASSISTANT TEACHER (DRAWING/FINE ARTS)", text: "ASSISTANT TEACHER (DRAWING/FINE ARTS)"},{value: "ASSISTANT TEACHER (FSSAP)", text: "ASSISTANT TEACHER (FSSAP)"},{value: "ASSISTANT TEACHER (ISLAMIC EDUCATION/ASSISTANT MOULAVI))", text: "ASSISTANT TEACHER (ISLAMIC EDUCATION/ASSISTANT MOULAVI))"},{value: "ASSISTANT TEACHER (JUNIOR)", text: "ASSISTANT TEACHER (JUNIOR)"},{value: "ASSISTANT TEACHER (JUNIOR/PRIMARY SECTION)", text: "ASSISTANT TEACHER (JUNIOR/PRIMARY SECTION)"},{value: "ASSISTANT TEACHER (LANGUAGE)", text: "ASSISTANT TEACHER (LANGUAGE)"},{value: "ASSISTANT TEACHER (PROMOTE)", text: "ASSISTANT TEACHER (PROMOTE)"},{value: "ASSISTANT TEACHER (SCIENCE)", text: "ASSISTANT TEACHER (SCIENCE)"},{value: "ASSISTANT TEACHER (SOCIAL SCIENCE)", text: "ASSISTANT TEACHER (SOCIAL SCIENCE)"},{value: "ASSISTANT TEACHER (WOODEN  TRADE)", text: "ASSISTANT TEACHER (WOODEN  TRADE)"},{value: "ASSISTANT TEACHER BANGLA", text: "ASSISTANT TEACHER BANGLA"},{value: "ASSISTANT TEACHER BIOLOGY SCIENCE", text: "ASSISTANT TEACHER BIOLOGY SCIENCE"},{value: "ASSISTANT TEACHER BUSINESS EDUCATION/COMMERCE", text: "ASSISTANT TEACHER BUSINESS EDUCATION/COMMERCE"},{value: "ASSISTANT TEACHER ENGLISH", text: "ASSISTANT TEACHER ENGLISH"},{value: "ASSISTANT TEACHER FIKSHA", text: "ASSISTANT TEACHER FIKSHA"},{value: "ASSISTANT TEACHER HOME ECONOMICS", text: "ASSISTANT TEACHER HOME ECONOMICS"},{value: "ASSISTANT TEACHER MATHEMATICS AND GENERAL SCIENCE", text: "ASSISTANT TEACHER MATHEMATICS AND GENERAL SCIENCE"},{value: "ASSISTANT TEACHER PART TIME", text: "ASSISTANT TEACHER PART TIME"},{value: "ASSISTANT TEACHER SCIENCE", text: "ASSISTANT TEACHER SCIENCE"},{value: "ASSISTANT TEACHER(HINDU/BUDDIST/CHRISTIAN)", text: "ASSISTANT TEACHER(HINDU/BUDDIST/CHRISTIAN)"},{value: "ASSISTANT VICE PRINCIPAL", text: "ASSISTANT VICE PRINCIPAL"},{value: "ASSOCIATE PROFESSOR", text: "ASSOCIATE PROFESSOR"},{value: "CHAIRMAN", text: "CHAIRMAN"},{value: "COMPUTER DEMONESTRATOR CUM-MECHANIC", text: "COMPUTER DEMONESTRATOR CUM-MECHANIC"},{value: "COMPUTER OPER.CUM-MACHANICS", text: "COMPUTER OPER.CUM-MACHANICS"},{value: "COMPUTER LAB ASSISTANT", text: "COMPUTER LAB ASSISTANT"},{value: "DAKHIL KARI", text: "DAKHIL KARI"},{value: "EBTEDAYEE HEAD", text: "EBTEDAYEE HEAD"},{value: "EBTEDAYEE JUNIOR MOULAVI", text: "EBTEDAYEE JUNIOR MOULAVI"},{value: "EBTEDAYEE JUNIOR TEACHER", text: "EBTEDAYEE JUNIOR TEACHER"},{value: "EBTEDAYEE QUARI", text: "EBTEDAYEE QUARI"},{value: "HEAD MAULANA", text: "HEAD MAULANA"},{value: "JUNIOR MOULAVI", text: "JUNIOR MOULAVI"},{value: "LAB ASSISTANT", text: "LAB ASSISTANT"},{value: "OSD", text: "OSD"},{value: "OTHER", text: "OTHER"},{value: "PRINCIPAL", text: "PRINCIPAL"},{value: "PROFESSOR", text: "PROFESSOR"},{value: "RESOURCE TEACHER ENGLISH ADDITIONAL CLASS", text: "RESOURCE TEACHER ENGLISH ADDITIONAL CLASS"},{value: "RESOURCE TEACHER MATH ADDITIONAL CLASS", text: "RESOURCE TEACHER MATH ADDITIONAL CLASS"},{value: "SUPPER", text: "SUPPER"},{value: "SUPPORT STAFF", text: "SUPPORT STAFF"},{value: "TEACHING ASSISTANCE", text: "TEACHING ASSISTANCE"},{value: "VICE PRINCIPAL", text: "VICE PRINCIPAL"}, {value: "Female", text: "Female"}],
  validate: function(value){
   if($.trim(value) == '')
   {
    return 'This field is required';
   }
  }
 });

 $('#employee_data').editable({
  container: 'body',
  selector: 'td.fdoj',
  url: "update.php",
  title: 'First Date of Joining',
  type: "POST",
  dataType: 'json',
  validate: function(value){
   if($.trim(value) == '')
   {
    return 'This field is required';
   }
  }
 });
 
  $('#employee_data').editable({
  container: 'body',
  selector: 'td.doj',
  url: "update.php",
  title: 'Date of Joining',
  type: "POST",
  dataType: 'json',
  validate: function(value){
   if($.trim(value) == '')
   {
    return 'This field is required';
   }
  }
 });

  $('#employee_data').editable({
  container: 'body',
  selector: 'td.dompo',
  url: "update.php",
  title: 'Date of MPO',
  type: "POST",
  dataType: 'json',
  validate: function(value){
   if($.trim(value) == '')
   {
    return 'This field is required';
   }
  }
 });

  $('#employee_data').editable({
  container: 'body',
  selector: 'td.dob',
  url: "update.php",
  title: 'Date of MPO',
  type: "POST",
  dataType: 'json',
  validate: function(value){
   if($.trim(value) == '')
   {
    return 'This field is required';
   }
  }
 });

 
});
</script>
`
