### ISSUE TITLE
X-editable Inline Dynamic Width

### ISSUE THREAD

**Issue by xfireize** [vitalets/x-editable#522]
Hello,

I am having trouble making inline x-editable width dynamic. Since I'm using responsive design, I don't wanna use static width as explained in #267. Has anyone ever solved this problem before? I'm not sure if 'inputclass' can solve this too.

After playing with the CSS, I can achieve what I want with changing width from auto to 100% in 'editable-inline/editable-container' and 'editable-input' class. However, I don't want to do this for every x-editable I have. I can change 'editable-input''s div in the template, but how about 'editable-inline/editable-container'?

I have some custom x-editable's and modified their 'tpl'. On some of these 'tpl', I have a 'row' class from bootstrap 3 with three 'col-lg-4' in them, spanning to 12. They are responsive and even extend the inline width. However, if I only have one column in one row, the width is not extended.

**Comment by aligajani** [comment]
hey man, doesn't work here @xfireize , how exactly did you do it.
