### ISSUE TITLE
Submiting value for select2 in tag mode

### ISSUE THREAD

**Issue by ArturKeyan** [vitalets/x-editable#565]
I am using X-Editable with _select2_ in _tag_ mode

```
 <a href="#" id="editableTag" data-name="Tags" data-type="select2" data-pk="3" data-original-title="Enter tags"></a> 


           $('#editableTag').editable({
                select2: {
                    tags: "tag1,tag2,tag3",
                    tokenSeparators: [",", " "]
                }              
            });
```

but after submiting value its submit like this 

```
name:Tags
value[]:tag1
value[]:tag2
pk:3
```

but as value I need all tags in string separated by comma 

```
name:Tags
value:tag1,tag2
pk:3
```

Can I somehow do this? and how?

**Comment by shalineetawar** [comment]
Hi,
You can use the "**separator**" property with value "**|**" (Or any other character which usually not be a part of the value) for getting the comma separator value as single value.
$('#editableTag').editable({
                select2: {
                    tags: "tag1,tag2,tag3",
                    tokenSeparators: [",", " "],
                    **separator: '|'**
                }              
            });
