### ISSUE TITLE
destroy doesn't work

### ISSUE THREAD

**Issue by assaqqaf** [vitalets/x-editable#61]
when I try to destroy I get the following error:

*_Uncaught TypeError: Cannot call method 'apply' of undefined *_

**Comment by GuanglinDu** [comment]
Our case (the row update feature):
(1) After one table cell value changes by X-editable (say, a user name), some of the other cells on the same row (say the mobile info, etc.) need to update accordingly (with a success callback). (2) Tried removing the old editable cache(?) with .editable("destroy") and, then, re-initialize the editing with .editable(obj) unsuccessfully.

We do need to refresh the editability after one or more nodes are changed by other JS code other than the X-editable, or the display in X-Editable UI and the source values are not in sync.
