### ISSUE TITLE
select2 inputs do not receive focus

### ISSUE THREAD

**Issue by ryanr23** [vitalets/x-editable#646]
The activate function should be overridden from the abstract implementation to call the select2 focus method.

This update to the prototype fixes the problem for me.

```
$.fn.editabletypes.select2.prototype.activate = function()
{
    this.$input.select2('focus');
}
```

**Comment by M4urice** [comment]
Still occurs with x-editable (bootstrap-editable.js to be precise) v1.5.1 for me.

**Comment by MarQuisKnox** [comment]
FIXED
