### ISSUE TITLE
How to localize the datepicker?

### ISSUE THREAD

**Issue by nicolasbernard** [vitalets/x-editable#67]
Hi,

I need to localize some parts of Datepicker UI in French.

On others places of my site, I use JqueryUI datepicker, and I can do: 

``` javascript
$.datepicker.regional['fr'] = {
        closeText: 'Fermer',
        prevText: 'Précédent',
        nextText: 'Suivant',
        currentText: 'Aujourd\'hui',
        monthNames: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
        monthNamesShort: ['Janv.', 'Févr.', 'Mars', 'Avril', 'Mai', 'Juin', 'Juil.', 'Août', 'Sept.', 'Oct.', 'Nov.', 'Déc.'],
        dayNames: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
        dayNamesShort: ['Dim.', 'Lun.', 'Mar.', 'Mer.', 'Jeu.', 'Ven.', 'Sam.'],
        dayNamesMin: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
        weekHeader: 'Sem.',
        dateFormat: 'dd/mm/yy',
        firstDay: 1,
        isRTL: false,
        showMonthAfterYear: false,
        yearSuffix: ''};
$.datepicker.setDefaults($.datepicker.regional['fr']);
```

But it don't apply to x-editable datepicker (which is a JQuery one right?).

I miss something or it's not localizable yet?

What's the easiest way to apply my translation today?
Editing source file seems ugly, can I apply my "regional['fr']" to another JS variable maybe?

**Comment by dkonayuki** [comment]
Yeah, me neither. 
`bdatepicker` works while `datepicker` does not.

**Comment by Sayayin** [comment]
Hello ickbinhier and dkonayuki,

The reason why bdatepicker works and datepicker does not must be because in your code is included the datepicker module, this module is allready included in x-editable module. Excluding de datepicker module solve the problem.
