### ISSUE TITLE
how to display listbox,we click x-editable type select for just one click.

### ISSUE THREAD

**Issue by ikolabo** [vitalets/x-editable#717]
for example: "Select, local array, custom display"
http://vitalets.github.io/x-editable/demo-bs3.html?c=inline

expected result:
1.clicking "not selected" , display listbox.

actutual result:
1.clicking "not selected", display selectbox.
2.clicking the selectbox, display listbox.

Do you know how to display listbox, when we click x-editable type select for just one click?

**Comment by bigdcoder** [comment]
Here is a quick example of how to use the 'shown' hook to take action after popup.  Below is an example of forcing open a select2 type after the x-editable popup is rendered.

```javascript
// hook on to 'shown' event
$('.editable-item').editable({/* options here */}).on('shown', function(event, editable) {
  // post-render function
  editable.input.postrender = function() {
    editable.input.$input.get(0).select(); // highlight text in input
    $('.select2-container').select2('open'); // open select2
  }
});
```

**Comment by ikolabo** [comment]
good!

for exmple 'open select'

$('.editable-item').editable({/* options here */}).on('shown', function(event, editable) {
    editable.input.postrender = function() {
    editable.input.$input.get(0).select(); // highlight text in input
    $('.select2-container').select2('open'); // open select2
  }
});

thank you , bigdcoder.
