### ISSUE TITLE
Checklist and empty value

### ISSUE THREAD

**Issue by brianchance** [vitalets/x-editable#72]
When I set the checklist to an empty value, I get an error from $.grep about length. Tracked it down to checklist's str2Value (checklist.js, line 57). 

If str is null or '', it returns a null value. That null value gets passed to value2HtmlFinal which passes the null to $.grep (line 99).

I think the easiest fix is to change line 57 from
`var reg, value = null;`
to
`var reg, value = [];`

Or maybe I am doing something wrong? Does an empty list (no boxes checked) need something else passed?

Brian

**Comment by lefty55104** [comment]
This still doesn't work for me.
