### ISSUE TITLE
Bootstrap3 X-Editable not working (not even in the demo)

### ISSUE THREAD

**Issue by IvoPereira** [vitalets/x-editable#722]
I'm trying to use the code in the documentation page however I am not being able to get it to work.

Documentation page: https://vitalets.github.io/x-editable/docs.html
My try: http://jsfiddle.net/vv8qL30u/1/

It gives me the error "Uncaught TypeError: Cannot read property 'defaults' of undefined".

Any suggestions on how to fix this?

Thanks!

**Comment by IvoPereira** [comment]
Forget it. Invalid markup.

**Comment by lewiyue** [comment]
@IvoPereira , sorry, i compared following two links:
http://jsfiddle.net/vv8qL30u/1/
http://jsfiddle.net/vv8qL30u/2/

Code is the same for me. But no content displayed in Result Part of http://jsfiddle.net/vv8qL30u/1/.

What do you mean for " Invalid markup: I was not closing the script tag.". Thanks.

**Comment by IvoPereira** [comment]
@lewiyue I was saying that in the first attempt I forgot to close the bootstrap-editable script tag, therefore the editable text was not showing up in result.

It is working now in second try with:

<script src="http://cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>

**Comment by lewiyue** [comment]
IC. Thanks @IvoPereira .
