### ISSUE TITLE
Custom DatePicker Library used with X-Editable?

### ISSUE THREAD

**Issue by jasondavis** [vitalets/x-editable#738]
Has anyone been able to use a custom Date Picker library (any of the available open source ones besides jQueryUI and Bootstrap)?

**Comment by mihael** [comment]
yes @jasondavis, ii used it with KendoUI, just had to write proper x-editable plugins and works like a charm:

KendoDateTimePicker:
https://gist.github.com/mihael/c90202b6663f379e4e63

KendoDatePicker:
https://gist.github.com/mihael/07c74157c8bec88fa861

**Comment by jasondavis** [comment]
@mihael Thanks for the response and code examples!  I am building a fairly advanced Project Management app in which every "Task" for a Project will be opened in the same HTML DOM window.  

So each time a new Task is opened, it is using the HTML in the DOM to re-use the Modal window.  So each time a Task is closed and a new one opened, I have to kill all my `x-editable` fields and then re-assign/build them with new data.

It's turning out pretty good so far but some of this stuff is tricky for me so this should help me a lot, thanks again for sharing!
