### ISSUE TITLE
Aaany way of changing source on select

### ISSUE THREAD

**Issue by sidewaysglance** [vitalets/x-editable#75]
I want to change the source on a Select - dependent on the value from a different Select.

I have tried various things, including using $('selector').editable('destroy') method & reinit on success, and $('selector').on('save', function(e, params) {...

I have not found a way of doing it.

Any help appreciated.

**Comment by Saeven** [comment]
Perfect!

**Comment by wagishsharma** [comment]
hi @vitalets , this will only work on type 'select', Is there anything similar for type 'select2'?
