### ISSUE TITLE
Add checkbox type for boolean values

### ISSUE THREAD

**Issue by juann-pierre-strauss** [vitalets/x-editable#761]
It would be beneficial to add a checkbox for boolean fields, e.g. Accept Agreement, etc. 
While it is possible to get the functionality using a dropdownlist type, it would be a much better UX to simply use a single checkbox.

**Comment by Cojad** [comment]
The docs section didn't mentioned but you can actually make such custom input on your own. You can check example at http://vitalets.github.io/x-editable/demo-bs3.html
The last one is a "custom input, several fields" which gives a very good example how to achieve what you want.
below is the core code to make custom input.
http://vitalets.github.io/x-editable/assets/x-editable/inputs-ext/address/address.css
http://vitalets.github.io/x-editable/assets/x-editable/inputs-ext/address/address.js

**Comment by Cojad** [comment]
If you don't want click to popup or inline. It might be easier just create a ajax checkbox with jquery. This example is very simple, it only need jquery to work.
http://jsfiddle.net/cojad/ktzn7hbq/1/

**Comment by juann-pierre-strauss** [comment]
Thank you for the example. Also, thank you for the suggested alternative. I will keep the custom input ability in mind in future.

**Comment by kodeine** [comment]
@Cojad 
i am using bootstrap-table and ediable extension.
What if i need 3 checkbox's each row without using inline or popup?

http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/editable.html
