### ISSUE TITLE
Combodate not working for the year 2016

### ISSUE THREAD

**Issue by moradrouaguy** [vitalets/x-editable#848]
Hi ! 
I get an issue with the combodate about the year, it's not showing me '2016' also in the official demo page it's not working.

Can anyone help me please ?

**Comment by moradrouaguy** [comment]
I fixed it,
The maxYear by default is 2015 that's why.

So I just added : maxYear: 2016

```combodate: {
    maxYear: 2016
}```

Something would be good is to have directly the year of the day by default for maxYear directly into the x-editable library.

**Comment by cara023** [comment]
:+1: TY!
