### ISSUE TITLE
not working with bootstrap table while filtering

### ISSUE THREAD

**Issue by kalu8** [vitalets/x-editable#850]
I´m Using this: 
https://github.com/wenzhixin/bootstrap-table

almost working ok, but when I search for one record, the x-editable is not working while filtering in bootstrap table. Any ideas?

**Comment by angelopaapa** [comment]
Same around here... Hope someone will advise

**Comment by Doogiemuc** [comment]
Just trying to help: After a lot of fiddling around, I gut x-editable up an running with the very powerfull datatables.net Library.   Bootstrap-Table also looks nice.   If x-editable is not working anymore after filtering, I'd guess, that most probably somehow a non initialized editable DOM element remains. I found that it is very important to call the inital .editable( { ... } ) call on the  correct DOM element.

**Comment by MarQuisKnox** [comment]
Use this:  https://api.jquery.com/on
