### ISSUE TITLE
Bootstrap-table with x-Editable

### ISSUE THREAD

**Issue by bhagirath1105** [vitalets/x-editable#863]
Guys, here is the problem
1. We load multiple pages
2. We have a drop down on one column where user selects the REASON for their inquiry
3. But when user does back and forth(i.e. Change Page from x to y), values selected in dropdown are not retained.

Help is appreciated.

**Comment by Allerion** [comment]
You need to make use of some sort of temporary storage functionality to retain information across page loads.

- Use sessions and store data in it (PHP $_SESSION or equivalent in another language)
- Use HTML5 localStorage (not suitable for older browsers)
- Make use of Ajax so you don't have page loads

**Comment by bhagirath1105** [comment]
Thank you Allerion. That is what we happened to do it. However i was expecting something at Plug in level to "Update Client Side Data". We wanted to update all data not just the Page user is looking at. For example, if we have 7 pages of 10 records per page, we wanted to GLOBALLY UPDATE ONE FIELD's value on all the pages.

However I appreciate your reply and we exactly implemented what you mentioned. Thx.
