### ISSUE TITLE
Ember-X-Editable

### ISSUE THREAD

**Issue by rwwagner90** [vitalets/x-editable#867]
I know you have angular-x-editable, but I found issues trying to use x-editable with Ember in the past, and I started working on building the same functionality from the ground up using Ember. Please check out what I have done so far https://github.com/shipshapecode/ember-x-editable

I'd love to get some community support working on an official Ember version. Please let me know your thoughts!

**Comment by lorvent** [comment]
Your demo http://shipshapecode.github.io/ember-x-editable/ shows a blank page to me

**Comment by rwwagner90** [comment]
@lorvent sorry about that, I had moved it from a personal repo to an organization one and renamed it and forgot to update everything. The demo should be working now.

**Comment by lorvent** [comment]
Yea, its working now but only @vitalets can add a link to your repo in readme i guess.

hope he will see and adds it to readme.

**Comment by vitalets** [comment]
@rwwagner90 do you want the link to be added to http://vitalets.github.io/x-editable/ or somewhere else ?
@lorvent I think you can. As a collaborator you can change `gh-pages` branch as you like. Exactly for related projects template is  here: https://github.com/vitalets/x-editable/blob/gh-pages/generator/templates/pages/index.hbs#L132

**Comment by rwwagner90** [comment]
@vitalets wherever you think it would be appropriate to list it. I just wanted to get it some more visibility and maybe some people will be interested in building it out further.

**Comment by vitalets** [comment]
ok, @lorvent could I ask you to update `gh-pages` as I mentioned before?

**Comment by lorvent** [comment]
Added! :+1:

**Comment by rwwagner90** [comment]
Awesome. Thanks guys!

**Comment by vitalets** [comment]
Thank you @lorvent !
