### ISSUE TITLE
popup clipping/positoning?

### ISSUE THREAD

**Issue by gbaumgart** [vitalets/x-editable#868]
The popup gets clipped: 

![image](https://cloud.githubusercontent.com/assets/1205100/13160190/4903015e-d696-11e5-83bd-a1b1619816b2.png)

is there a trick or option to overcome this? I am aware that bootstrap itself also never cared much about this problems (dropdown-clipping) and most use - cases don't need it neither fixed. I also know that the popup actually must go into the body element to fix this, but of course you would need to make it 'follow' the target which opens a whole set of new problems (still solvable and better than now)

any thoughts?

**Comment by gbaumgart** [comment]
most of the cases, extending position for one more dimension would do it: 'top-left'...

**Comment by gbaumgart** [comment]
Given the amount of open issues, it's unlikely that this gonna be fixed, right? 

what a pity. this lib won't work with advanced apps
![image](https://cloud.githubusercontent.com/assets/1205100/13184144/73e9b2e2-d73a-11e5-9cb4-20609fee05c5.png)

**Comment by lorvent** [comment]
If you think, you can fix something....then send PR

**Comment by gbaumgart** [comment]
don't think so, just realizing that its easier to fix on my side. but basically its as described, the popup must go into <body> directly and then follow the target. that worked with tws-nabar too for me.
