### ISSUE TITLE
Any plans to support Angular2

### ISSUE THREAD

**Issue by soorireddy** [vitalets/x-editable#870]
It is very cool feature to have  in angular 2

**Comment by simpadmin** [comment]
did you read the website?! https://vitalets.github.io/angular-xeditable/

**Comment by soorireddy** [comment]
Not followed ,what you want me to read.
I have implemented x-editable including (password,request raised by me
)with angular1.x ,now thinking of  implementing same angular2 with type
script(tsd),but I am not sure how to inject  this.

**Comment by jculverwell** [comment]
Would also love to know if you have any plans for Angular 2.  Thank you

**Comment by lorvent** [comment]
if its being developed by any other person, its welcome
official team has no plans.

**Comment by soorireddy** [comment]
Yes I am working on template with angular2,material2, ng2 uploader,ng2
translator,ng2 maps.
On Jul 25, 2016 5:25 PM, "Jim Culverwell" <notifications@github.com> wrote:

Would also love to know if you have any plans for Angular 2. Thank you

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/vitalets/x-editable/issues/870#issuecomment-234933217>,
or mute the thread

**Comment by MarQuisKnox** [comment]
Not planned at this time

**Comment by ClementRajesh** [comment]
Is x-editable part of angular?
