### ISSUE TITLE
NPM package issue with x-editable 

### ISSUE THREAD

**Issue by viniprima** [vitalets/x-editable#874]
Is someone facing issues with npm package? Please help

**Comment by lorvent** [comment]
can you elaborate?

**Comment by simpadmin** [comment]
Looks good here:

$ npm install x-editable
npm http GET https://registry.npmjs.org/x-editable
npm http 200 https://registry.npmjs.org/x-editable
npm http GET https://registry.npmjs.org/x-editable/-/x-editable-1.5.1.tgz
npm http 200 https://registry.npmjs.org/x-editable/-/x-editable-1.5.1.tgz
x-editable@1.5.1 node_modules/x-editable
$
$ cd node_modules/
$ ls
x-editable
$ cd x-editable/dist/bootstrap3-editable
$ du -a
24      ./css/bootstrap-editable.css
28      ./css
76      ./js/bootstrap-editable.min.js
228     ./js/bootstrap-editable.js
308     ./js
4       ./img/clear.png
4       ./img/loading.gif
12      ./img
