### ISSUE TITLE
use datatable() and initial rows display less than "all" (-1)

### ISSUE THREAD

**Issue by simpadmin** [vitalets/x-editable#877]
Hi,

I just noticed on my query form if the initial display is lower than ALL the rows returned in the query, if I change the number of rows displayed then the x-editable elements after that amount of rows are not editable, they have a solid underline. If I change the initial display to "ALL" -1 then if I make the display
to less amount of rows then all the x-editable elements are displayed and can go back and forth. 

My data table settings are:

`$(document).ready(function() {
    // Setup - add a text input to each footer cell
    $('#mytable1 thead th').each( function () {
        var title = $(this).text();
        $(this).html( '<input type="text" placeholder="Search '+title+'" />' );
    } );
    $('#mytable1 tfoot th').each( function () {
        var title = $(this).text();
        $(this).html( '<input type="text" placeholder="Search '+title+'" />' );
    } );

```
// DataTable
var table = $('#mytable1').DataTable({
    'paging':   true,  // Table pagination
    'ordering': true,  // Column ordering
    'info':     true,  // Bottom left status text
    aLengthMenu: [
      [-1, 10, 50],
      ["All", 10, 50]
    ],
    // Text translation options
    // Note the required keywords between underscores (e.g _MENU_)
    oLanguage: {
        sSearch:      'Search all columns:',
        sLengthMenu:  '_MENU_ records per page',
        info:         'Showing page _PAGE_ of _PAGES_',
        zeroRecords:  'Nothing found - sorry',
        infoEmpty:    'No records available',
        infoFiltered: '(filtered from _MAX_ total records)'
    }
});

// Apply the search
table.columns().every( function () {
    var that = this;

    $( 'input', this.footer() ).on( 'keyup change', function () {
        if ( that.search() !== this.value ) {
            that
                .search( this.value )
                .draw();
        }
    } );
    $( 'input', this.header() ).on( 'keyup change', function () {
        if ( that.search() !== this.value ) {
            that
                .search( this.value )
                .draw();
        }
    } );
} );
```

`
My x-editable settings are:

`    //turn to popup mode
    $.fn.editable.defaults.mode = 'popup';

```
$('#mytable1 a').editable();
```

`

If I change:

`aLengthMenu: [
          [-1, 10, 50],
          ["All", 10, 50]
        ],`

to:

`aLengthMenu: [
          [10, 50, -1],
          [10, 50, "ALL"]
        ],`

And then select 50 rows or ALL the additional rows x-editable elements are not editable. The underline is solid as opposed to broken on the editable elements (above). Thanks!

**Comment by Doogiemuc** [comment]
I didn't test it, but I think I can help: Your call `$('my table a).editable()` only initializes x-editable on all the **currently visible** links. That is the rows that are currently shown. If your table has more rows that can be shown via paging, then you have to re-initilaize the x-editable fields.    You could listen for datatables's page events.  I hope that helps

**Comment by simpadmin** [comment]
@Doogiemuc sounds reasonable, I will review the page events and see if this newbie can figure out how to "listen" for them when I get a chance, thanks!
