### ISSUE TITLE
Array order not respected in checklist. 

### ISSUE THREAD

**Issue by CaMer0n** [vitalets/x-editable#883]
@vitalets , thanks for this great package. I have no issues with it other than this: 

When an array is sent to x-editable sorted alphabetically. x-editable rearranges the order based on key value. 

http://jsfiddle.net/wmc0ck6h/

I'm guessing it's an easy one to fix?

**Comment by hbalagtas** [comment]
Having the same issue as well, I need to display a list of user id's but they are getting sorted by their actual id's and not alphabetically.

**Comment by hbalagtas** [comment]
Just found something in the docs https://vitalets.github.io/x-editable/docs.html

It seems the array has to follow the {value:1, text:foo} format otherwise sorting is not guaranteed. Made changes to my code and the listing is showing alphabetically now.

**Comment by Trimakas** [comment]
Shoot, I'm not seeing this in the doc's..
