### ISSUE TITLE
error info:success.call is not a function 

### ISSUE THREAD

**Issue by jy05568536** [vitalets/x-editable#884]
when type='select' and save data,have a error,success.call is not a function

**Comment by jy05568536** [comment]
value2html: function (value, element, display, response) {
            var deferred = $.Deferred();
	        **success = deferred.then(function () {**
	            if(typeof display === 'function') {
	                //custom display method
	                display.call(element, value, this.sourceData, response); 
	            } else {
	                this.value2htmlFinal(value, element);
	            }
	            deferred.resolve();
	       });
===============
the bolder code is error,
bootstrap-editable.js:2578 Uncaught ReferenceError: success is not defined

**Comment by philwu** [comment]
Same problem here. I didn't see 'success' in the docs. How should I define it?
here is my code.
$(function(){
	$("#myEditor").editable({
	name:'name',
	type:'select',
	pk:2,
	title:'Select one',
	url:'returnOk.php',          //this file always return httpcode 200
	source:[{"value":"1","text":"VALUE 1"},{"value":"2","text":"VALUE 2"}],
	value:1,
	success:function(data,config){
              alert("ok");   //this line works
        }
	});
});

here is a live of my code: http://52.64.25.92/login/test.html

**Comment by philwu** [comment]
@jy05568536 Did you fix it?
