### ISSUE TITLE
Laravel 5.2: TokenMismatchException in VerifyCsrfToken.php line 67:

### ISSUE THREAD

**Issue by ahmedsliman** [vitalets/x-editable#893]
I try to update editable field but Laravel return with this error

`TokenMismatchException in VerifyCsrfToken.php line 67:`

**Comment by lorvent** [comment]
thats not at all related to x-editable

token mismatch comes because for every post/patch etc requests you need to pass token in laravel

either you can disable that or pass token along with your other requests.
