### ISSUE TITLE
select type gives "success is not defined"

### ISSUE THREAD

**Issue by philwu** [vitalets/x-editable#897]
When saving data with type='select', it gives an error that "success is not defined"
Same problem mentioned in [issue#884](https://github.com/vitalets/x-editable/issues/884) but it was closed with no explanation.

here is a live of my code: http://52.64.25.92/login/test.html

here is my code:
`$("#myEditor").editable({
       name:'name',
       type:'select',
       pk:2,
       title:'Select one',
       url:'returnOk.php',             //this file always return httpcode 200
       source:[{"value":"1","text":"VALUE 1"},{"value":"2","text":"VALUE 2"}],
       value:1,
       success:function(data,config){
            alert("ok");                   //this line works
       }
});`

**Comment by wenzhixin** [comment]
Same problem: http://issues.wenzhixin.net.cn/bootstrap-table/#issues/986.html

This PR cause the problem: https://github.com/vitalets/x-editable/pull/876 @vitalets @lorvent.
[Do not edit files of dist directly!](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#pull-requests)

**Comment by wenzhixin** [comment]
@philwu you can use this version: https://github.com/vitalets/x-editable/blob/76cdd530919d5faa8e411eabc7b28d67761bcec0/dist/bootstrap3-editable/js/bootstrap-editable.js

**Comment by lorvent** [comment]
hmm, @wenzhixin 
can you send a fix PR?

**Comment by wenzhixin** [comment]
#898
