### ISSUE TITLE
Automatically Select All in textbox editable

### ISSUE THREAD

**Issue by joshglenn** [vitalets/x-editable#910]
What would be the best way to Automatically Select All text in a textbox editable so that a user doesn't have to click for the popover, then double-click a particular text string in order to edit it?

**Comment by drm-code** [comment]
That would be a very useful feature, actually I need it now :D

**Comment by joshglenn** [comment]
it may be that it is not a feature that needs to implement. It may be possible using JavaScript and/or jQuery functionality. If someone could give some insight into how it could be accomplished, that would be excellent!

**Comment by swrobel** [comment]
Duplicate. Try searching next time! https://github.com/vitalets/x-editable/issues/330
