### ISSUE TITLE
Select adds an empty option.

### ISSUE THREAD

**Issue by salehliam** [vitalets/x-editable#916]
Hello Guys, 

Every time I build an editable field of type **select** with a given source it adds an empty option in the begining of the list.  Is there a way to remove it?

![image](https://cloud.githubusercontent.com/assets/8984371/16803916/63cf8738-4909-11e6-89ab-d0eefe59983f.png)
Thanks!

**Comment by inoks** [comment]
@salehliam Seems you have not provide initial value, or you initial value mismatch with available options.
Can you provide example of you case on https://jsfiddle.net/ ?

**Comment by salehliam** [comment]
Thanks @inoks. You are right there was no initial value since I wasn't sure how to set it and still have some problems with it.

http://jsfiddle.net/fsh97rwL/8/
