### ISSUE TITLE
cols in textarea

### ISSUE THREAD

**Issue by chriship** [vitalets/x-editable#922]
Any chance of adding a cols attribute option to the textarea?

**Comment by lorvent** [comment]
how that is related to x-editable?
you can do that using html  or using javascript also right.

**Comment by chriship** [comment]
Sorry, was not particularly clear with my comment.

On lines 3025 and 3043 here: https://github.com/vitalets/x-editable/blob/master/dist/bootstrap3-editable/js/bootstrap-editable.js it shows that I can enter a rows attribute when using a textarea as the editing input. 

I was just wondering whether you could add a cols attribute too for more control over the size of the textarea?

**Comment by lorvent** [comment]
I get you now,
but unfortunately we don't have such option.

if you use bootstrap, you can restict with col-*

**Comment by chriship** [comment]
ok thanks!
