### ISSUE TITLE
Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.

### ISSUE THREAD

**Issue by michalzimniak** [vitalets/x-editable#924]
I got warnings:

bootstrap-editable.js:666 Uncaught InvalidStateError: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.

when setting editable to <a data-type="number">

**Comment by MonrealRyan** [comment]
+1

**Comment by mbtronics** [comment]
Dupe: https://github.com/vitalets/x-editable/issues/939
