### ISSUE TITLE
Undefined Is Not An Object: Karma Test Runner Conflicts with bootstrap-editable library

### ISSUE THREAD

**Issue by jflayhart** [vitalets/x-editable#933]
I know there are a lot of threads about this, but I haven't been able to find nor understand any solutions regarding this particular case and alot of them refer to some type of Angular or other unrelated issue.

I am running node v6.5.0, npm 3.10.6 with Karma test runner in my ReactJS project. The problem is as soon as I introduced the x-editable library I am unable to run `npm test`. Removing the library allows the karma test runner to run successfully. Although with the xeditable library I receive the following error:

```
to be executed: babel-node ./node_modules/karma/bin/karma start build/karma.conf
app:config Creating default configuration. +0ms
app:config Looking for environment overrides for NODE_ENV "test". +38ms
app:config No environment overrides found, defaults will be used. +5ms
app:webpack:config Create configuration. +715ms
app:webpack:config Apply ExtractTextPlugin to CSS loaders. +53ms
app:karma Create configuration. +1ms

START:
26 09 2016 22:13:30.442:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
26 09 2016 22:13:30.444:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
26 09 2016 22:13:30.539:INFO [launcher]: Starting browser PhantomJS
26 09 2016 22:13:30.987:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#yyxiFHE-r0V3e2a-AAAA with id 44774801
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
TypeError: undefined is not an object (evaluating 'a.fn.popover.Constructor')
at webpack:///src/lib/bootstrap-editable.min.js:1:0 <- tests/test-bundler.js:162134

Finished in 0.753 secs / 0 secs

SUMMARY:
✔ 0 tests completed
npm ERR! Test failed.  See above for more details.
```

What gives?

**Comment by jflayhart** [comment]
Ok, after countless hours, it turns out I needed to have required bootstrap.min.js to my Karma config `files: []` dependencies. I hadn't needed to do that until this plugin. Hopefully this helps someone else. I figured it was a deps issue, but couldn't understand why!

**Comment by dusterio** [comment]
Had the same issue today and adding to files[] didn't help (even though files got imported correctly). I had to add a redundant import 'bootstrap/dist/js/npm' to my component that uses x-editable to fix this
