### ISSUE TITLE
How to validate data from inputs in Laravel

### ISSUE THREAD

**Issue by aronzillo** [vitalets/x-editable#952]
In your example you have:
```
public function update(Request $request, $id)
{
        $serie = Serie::findOrFail($id);
        $name = $request->get('name');
        $value = $request->get('value');
        $serie->$name = $value;
        return $serie->save();
}
```
and it works fine, but I need validate data and return errors

**Comment by sudomabider** [comment]
You need to change the request data from `name: $name` and `value: $value` into simply `$name: $value` which then Laravel can understand. For example you can do something like this before you validate:

```
// copy values first in case the data is actually called 'name'
list($name, $value) = [$request->input('name'), $request->input('value')];

$request->request->remove('name');
$request->request->remove('value');
$request->request->set($name, $value);
```
Note `$request->request` is the actual underlying request parameter bag.

You can also create a base xeditable request that automagically does this before validation. And simply extend this class whenever suitable.
