### ISSUE TITLE
Post process action

### ISSUE THREAD

**Issue by jeanmonod** [vitalets/x-editable#958]
I'm looking for a callback, or an event that is trigger when the x-editable job is done. I tried with method `success` and also with event `save`, but in both case the HTML of my page is not yet renderer. What is the way to go for this? Is there an event `unload` or `finalised` somewhere?

Thanks in advance for the feedback

**Comment by MarQuisKnox** [comment]
At which point exactly? After saving?

**Comment by jeanmonod** [comment]
Yes, after saving. I already tried with the `success` callback. But at this time, the `span` I just edit still contain the old value. I'm looking for a callback that occur after x-editable job is completely done. In that case after the new value is inserted into the DOM.

**Comment by MarQuisKnox** [comment]
Please try this:  https://github.com/vitalets/x-editable/blob/master/dist/bootstrap-editable/js/bootstrap-editable.js#L1203

LMK if it works or not. Otherwise this ticket will be closed after 14 days of no response to keep the number of open tickets down. Now we are over 500 open issues. 

Thanks.

**Comment by jeanmonod** [comment]
No, on `save` have the same issue, the editable element is not yet updated. But I finally managed to have it work with the `hidden` event. This one is trigger after the DOM gets updated.
Thanks for support
