### ISSUE TITLE
Set the Default Branch to 'dev'

### ISSUE THREAD

**Issue by MarQuisKnox** [vitalets/x-editable#961]
@vitalets:  Can you please set the default branch to 'dev'? https://help.github.com/articles/setting-the-default-branch — this is because it seems that no one reads that they should submit PRs to 'dev' & not 'master', which is currently the default branch.

Also do you have anything against renaming 'dev' to 'develop'? I want to use Git Flow:  http://danielkummer.github.io/git-flow-cheatsheet 

Thanks.

**Comment by vitalets** [comment]
hi @MarQuisKnox !
I think maybe remove `dev` branch at all? It seems overhead for me - we can just commit to `master` and tag releases. 

/cc @lorvent ?

**Comment by lorvent** [comment]
yes, that also works fine.

since most of the people getting files from npm,bower etc...they can get stable versions.

and master is for all changes.

---

having both branches is also fine as their names represents meanings easily

master - stable, release version
dev - unstable, development version

**Comment by MarQuisKnox** [comment]
Hi @vitalets:

I recommend this:

1. Rename 'dev' to 'develop'. This is because 'develop' is the default name that 'git-flow' expects for the Development branch.
2. Set 'develop' as the default branch. This is because people are still submitting PRs to 'master'.
3. Keep the 'master' branch.
4. Use the GitFlow workflow:  http://danielkummer.github.io/git-flow-cheatsheet
5. GitFlow does not have to be used. Devs can still simply submit PRs to the 'develop' branch.

@lorvent is correct about 'master' & 'dev' branches.

**Comment by vitalets** [comment]
@MarQuisKnox ok.
Create `develop` branch and I will make it default.

**Comment by MarQuisKnox** [comment]
@vitalets:  OK, done:  https://github.com/vitalets/x-editable/tree/develop

**Comment by vitalets** [comment]
changed default branch to `develop`

**Comment by MarQuisKnox** [comment]
Thanks!

**Comment by MarQuisKnox** [comment]
@vitalets:  Later we also need to delete the `dev` branch after merging any outstanding Pull Requests:  http://stackoverflow.com/questions/32658070/what-happens-to-existing-pull-requests-when-the-target-branch-is-deleted

For further clarification, `develop` & `dev` are exact duplicates right now, but we should not remove `dev` until the PRs are merged.

**Comment by vitalets** [comment]
Agreed. Thanks man! 👍

**Comment by MarQuisKnox** [comment]
No problem
