### ISSUE TITLE
Bootstrap v4.0.0-alpha.6 support?

### ISSUE THREAD

**Issue by hansen-florian** [vitalets/x-editable#973]
First of all, great work!

When will Bootstrap 4 work and there will be no problems with the pop-up?

**Comment by MarQuisKnox** [comment]
Hi, no support until the final version is released. 
Thanks.

**Comment by ilramdhan** [comment]
Bootstrap 4 is worked for me. Check [https://github.com/vitalets/x-editable/issues/1189#issue-2472436889](url)
