### ISSUE TITLE
How to set default value in select option

### ISSUE THREAD

**Issue by aravindtga** [vitalets/x-editable#98]
I am creating the editable combo as follows...
$(this).editable({
                title: 'Select priority',
                type:'select',
                placement:"right",
                emptytext: '.',
                toggle:'click',
                send:"always",
                source:[
                        {value:3,text:'Low'},
                        {value:2,text:'Medium'},
                        {value:1,text:'High'},
                        ]
 });

I want to set the  value 1(text:'High ) as default ...How can i do this....

**Comment by marta001** [comment]
Eons later...
@poorman question, simply add data-value="" to 
"< a id="feed_type_id" class="editable editable-click" href="#" >Medium< /a >"
