### ISSUE TITLE
How can I  get the value of select input after updating  it locally and not send it to server?

### ISSUE THREAD

**Issue by lazybonee** [vitalets/x-editable#980]
$(".name").editable({
	mode: "inline",
	success: function(response, newValue) {
			console.log(newValue);
                        /*userModel.set('username', newValue); //update backbone model*/
			},
        error: function(){
		console.log("error");
		}
	})
I take  it like described in the document,set url to be empty and process value in success handler,but the success handler is not called,neither the error handler.what's wrong?

**Comment by MarQuisKnox** [comment]
Please setup a demo:  https://jsfiddle.net

**Comment by lazybonee** [comment]
Oh I have solved this problem,I find the value can be fetched with $(".name").editable(‘getValue')

**Comment by lazybonee** [comment]
Oh I have solved this problem,I find the value can be fetched with $(".name").editable(‘getValue')
