### ISSUE TITLE
How can I setup the images path?

### ISSUE THREAD

**Issue by GildedHonour** [vitalets/x-editable#986]
I've put the images loading.gif and clear.gif in a location which differs from the default one. How can I tell x-editable to use a certain location to load them?

**Comment by MarQuisKnox** [comment]
Edited the associated CSS file

**Comment by GildedHonour** [comment]
Who edited?

**Comment by MarQuisKnox** [comment]
Sorry, typo. 
Edit the CSS files that you are using. Example:  https://github.com/vitalets/x-editable/tree/develop/dist/bootstrap3-editable/css
