### ISSUE TITLE
Submit multiple editable element fired by an external button

### ISSUE THREAD

**Issue by IEfucker** [vitalets/x-editable#989]
I made this
http://jsfiddle.net/Jack_bay/xBB5x/13603/
submit fired by click an external button

if it has multiple editable element(no comment the second element), it would work fine.
but if I comment one and left a single element, the post url would not be "**/posttest**", but current window's **location.href.**

is it a bug, or I missed something .

**Comment by IEfucker** [comment]
I read the code
https://github.com/vitalets/x-editable/blob/develop/dist/bootstrap3-editable/js/bootstrap-editable.js#L2060
here, if single element, url would be from init options when multiple would be from config arguments.
it is not a bug sure enough. but the doc is unclear absolutely.
hope you would notice this

**Comment by MarQuisKnox** [comment]
This is the normal default behavior of any web component. If a target URL is not specified then it will use the current URL. For example:  `<a href="">example.com</a>`

**Comment by IEfucker** [comment]
funny

**Comment by MarQuisKnox** [comment]
So, I reread your example to see what you are trying to do. 
For the second button, you could get the value of the x-editable field & use your own logic to save it:  https://vitalets.github.io/x-editable/docs.html#editable (use the `getValue()` function) or you can force a click on x-editable's native save button.
